### ISSUE TITLE
VkpObservationHeartrate profil

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/VkpObservation#4]
Utgangspunkt i hl7 [heartrate](http://hl7.org/fhir/StructureDefinition/heartrate)
- [ ] Krav om FNR/DNR/FHNR for subject
- [ ] Krav til performer FNR
- [ ] Angi frivillig slice for SNOMED koder observation.code
- [ ] Skal det oppgis referanseverdier?
- [ ] Eksempel som tester profilen (snomedkoder)

Foreløpig koding:

|Type observasjon|undertype|Profil|LOINC|SNOMED|
|----------------|---------|------|-----|------|
|puls||VkpObservationHeartrate|8867-4 heart-rate|364075005 Heart Rate|

**Comment by rockphotog** [comment]
TODO @rockphotog : Utvikle beste praksis for referanse til identifier ("logisk referanse"), lage egen *best practice*-side og issue der. 
EDIT: https://github.com/HL7Norway/best-practice/issues/100 

> Krav om FNR/DNR/FHNR for subject

Denne må vel være tekstlig, da det vel ikke kan representeres i profilen annet enn å peke på no-patient (som vi kanskje ikke gjør lengre?)

> Krav til performer FNR

Som over + logisk referanse. Dok + eksempel. 

> Skal det oppgis referanseverdier?

God spørsmål. Jeg tror ikke det er vanlig med referanseverdier for hjertefrekvens. Hvilepuls, makspuls krever egne observasjoner. Annet er regnet ut fra alder og kjønn, og bør ikke overføres.

**Comment by rockphotog** [comment]
Ligger i branch dev-heartrate inntil videre:
https://github.com/HL7Norway/VkpObservation/blob/dev-heartrate/VkpObservation/input/fsh/profiles/VkpObservationHeartrate.fsh

**Comment by thomiz** [comment]
Ikke så fort, du kan legge inn identifier krav slik som i eksisterende profiler:  @rockphotog   
[VkpObservationBloodpressure](https://github.com/HL7Norway/VkpObservation/blob/master/VkpObservation/input/fsh/profiles/VkpObservationBloodpressure.fsh)  
[VkpObservationOxygensat](https://github.com/HL7Norway/VkpObservation/blob/master/VkpObservation/input/fsh/profiles/VkpObservationOxygensat.fsh)
